In [6]:
import numpy as np
arr = np.array([1,2,3,4,5,20,21,27,31])
# Reverse the array, using slicing
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr)

Original array: [ 1  2  3  4  5 20 21 27 31]
Reversed array: [31 27 21 20  5  4  3  2  1]


In [3]:
#using numpy
import numpy as np
#assigning the data
arr1 = np.array([[2,4,8],[3,6,9]])
arr2 = np.array([[10,12,14],[12,15,18]])
result=np.concatenate((arr1,arr2),axis=0)
print("concatenated array along rows (axis=0):\n", result)

concatenated array along rows (axis=0):
 [[ 2  4  8]
 [ 3  6  9]
 [10 12 14]
 [12 15 18]]


In [4]:
import numpy as np
arr=np.array([[],[]])
arr1=np.array([[],[]])
can=np.concatenate ((arr,arr1),axis=1)
print("concatenate with axis=1")
print(can)

concatenate with axis=1
[]
