In [12]:
#using numpy
import numpy as np
arr=np.array([1,2,3,4,5,20,21,27,31])
#reversing the given data
reversed_arr=arr[::-1]
print("original array", arr)
print("reversed array", reversed_arr)

original array [ 1  2  3  4  5 20 21 27 31]
reversed array [31 27 21 20  5  4  3  2  1]


In [7]:
#using numpy
import numpy as np
#assigning the data
arr1 = np.array([[2,4,8],[3,6,9]])
arr2 = np.array([[10,12,14],[12,15,18]])
result=np.concatenate((arr1,arr2),axis=0)
print("concatenated array along rows (axis=0):\n", result)

concatenated array along rows (axis=0):
 [[ 2  4  8]
 [ 3  6  9]
 [10 12 14]
 [12 15 18]]


In [15]:
import numpy as np
arr = np.array([[1,5],[6,7]])
arr1 = np.array([[8,19],[22,25]])
can = np.concatenate((arr,arr1),axis=1)
print("concatenate with axis")
print(can)

concatenate with axis
[[ 1  5  8 19]
 [ 6  7 22 25]]
