In [34]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
# Reverse the array using slicing
reversed_arr = arr[::-3]
print("Original array:", arr)
print("Reversed array:", reversed_arr)


Original array: [1 2 3 4 5]
Reversed array: [5 2]


In [28]:
import numpy as np

# Create two 2D arrays with the same number of columns
arr1 = np.array([[2, 4, 8],[3, 6, 9]])
arr2 = np.array([[10, 12, 14],[12, 15, 18]])
# Concatenate along rows (axis 0)
result = np.concatenate((arr1, arr2), axis=0)

print("Concatenated array along rows (axis 0):\n", result)
   

Concatenated array along rows (axis 0):
 [[ 2  4  8]
 [ 3  6  9]
 [10 12 14]
 [12 15 18]]


In [33]:
import numpy as np
arr=np.array([[2,6],[7,8]])
arr1=np.array([[6,9],[1,3]])
can=np.concatenate ((arr,arr1),axis=1)
print("concatenate with axis=1")
print(can)

concatenate with axis=1
[[2 6 6 9]
 [7 8 1 3]]


In [ ]:




+++